# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Create configuration file
      run: |
        touch configuration.properties
        echo base_uri=${{ secrets.API_KEY }} >> configuration.properties
        echo profile_id=${{ secrets.PROFILE_ID }} >> configuration.properties

    - run: mkdir test-results
    - run: cat configuration.properties
    - name: Build and Test
      run: mvn verify --file pom.xml
      # upload the results to Calliope.
    - name: Upload results to Calliope
      run: curl -X POST
        -H "x-api-key:${{ secrets.API_KEY }}"
        -H "multipart/form-data"
        -F "file[]=@test-results/output.json"
        "https://app.calliope.pro/api/v2/profile/${{ secrets.PROFILE_ID }}/import/cucumber?os=myos&platform=myplatform&build=mybuild"
